# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "product-badge"
client_id = "f1fb5ae772e26aaa82ef60a062fe8ad0"
application_url = "https://grades-qualifications-exactly-problems.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_metaobjects"

[auth]
redirect_urls = [
  "https://grades-qualifications-exactly-problems.trycloudflare.com/auth/callback",
  "https://grades-qualifications-exactly-problems.trycloudflare.com/auth/shopify/callback",
  "https://grades-qualifications-exactly-problems.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ana1992.myshopify.com"
