# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Product Badge"
client_id = "fdbba2166edfb100f0b20236745629e3"
application_url = "https://charity-glasses-visit-wheel.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_metaobjects,write_discounts"

[auth]
redirect_urls = [
  "https://charity-glasses-visit-wheel.trycloudflare.com/auth/callback",
  "https://charity-glasses-visit-wheel.trycloudflare.com/auth/shopify/callback",
  "https://charity-glasses-visit-wheel.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ana1992.myshopify.com"
