# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "product-badge"
client_id = "91f35fe981a85c88903517b12c7df2c8"
application_url = "https://sen-jefferson-ae-lands.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_metaobjects,write_discounts"

[auth]
redirect_urls = [
  "https://sen-jefferson-ae-lands.trycloudflare.com/auth/callback",
  "https://sen-jefferson-ae-lands.trycloudflare.com/auth/shopify/callback",
  "https://sen-jefferson-ae-lands.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ana1992.myshopify.com"
